### ISSUE TITLE
Typo in file Changelog

### ISSUE THREAD

**Issue by zhenik** [pdmthorsrud/web_crawler#14]
## What is the issue?
Typo in file. 

## Suggestion(s)/solution(s) [Optional]
`CHANGELOD.md` to `CHANGELOG.md`

## Checklist (after created issue)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by pdmthorsrud** [comment]
God, I swear I changed that. TYVM!

**Comment by pdmthorsrud** [comment]
Hold up, I did actually fix it in https://github.com/pdmthorsrud/web_crawler/pull/13

Just hadn't merged it just yet :D
